package http

const (
	CONST_HTTP_STATUS_MSG_500 = "UNEXPECTED INTERNAL ERROR, CHECK BACK LATER!"
	CONST_HTTP_STATUS_MSG_400 = "ONE OR MORE REQUIRED PARAMS ARE MISSING OR INVALID!"
	CONST_HTTP_STATUS_MSG_200 = "OK"
)
